### PR TITLE
feat: add binary script

### PR DESCRIPTION
**Pull request by fazibear**
Add executable file. You can use this packages as a tool in other editors that supports LSP.

### CODE REVIEW

**Comment by fazibear** [comment]
Need to check it makes sense at all ;)

**Comment by jfcherng** [comment]
That's what we are doing. https://github.com/TerminalFi/LSP-copilot/blob/78c3f492f63ccfa755b1c7716f548333cfd0e1cc/plugin/plugin.py#L84-L91

**Comment by jfcherng** [comment]
But your PR makes sense because copilot.vim actually changes it's directory structure. So making a fixed path binary is better.

**Comment by jfcherng** [comment]
Thanks.

**Comment by jfcherng** [comment]
Fyi, `1.9.2` has been released.

**Comment by jfcherng** [comment]
Hi @fazibear, do you have an idea why `bin/copilot-node-server` doesn't work in v1.24.0 but `copilot/dist/agent.js` works?

**Comment by jfcherng** [comment]
I am going to remove `bin/` since it's not working. Removing it reduces confusion.

**Pull request merged**
